### PR TITLE
Initial repo structure

### PR DESCRIPTION
**Pull request by ilkamo**

### CODE REVIEW

**Comment by redsolver** [comment]
I would add that a `Post` objects always need to be part of a `Page`/`Feed` object (not sure about the name yet) because otherwise it lacks important information like the user who posted it

**Comment by ilkamo** [comment]
> I would add that a `Post` objects always need to be part of a `Page`/`Feed` object (not sure about the name yet) because otherwise it lacks important information like the user who posted it

@redsolver don't you think this information can be included as a parameter of the post or in the metadata of the post? In a feed (with posts from users you follow), you can have posts with different authors.

However, this PR is just to bootstrap and start a discussion. The rest can be added and edited when we commit models.

**Comment by redsolver** [comment]
Some context: Having every single post in one skyfile is quite inefficient, because you would need to make 1 HTTP request for every single post in a feed. That's the reason why there are "pages", where every page contains multiple posts. This page with posts on it is always controlled by a single user and then aggregated later to a "visible feed" client-side. If the user wants to reference/repost a post from another user, they don't "copy" it, but instead just link to it. So all posts in the user's feed/page are from the same user. (even if they are reposts)

**Comment by ilkamo** [comment]
@redsolver I got the point and I agree with you. What do you think about the name "_stream_"? It sounds more generic and we can put each type of data under a user stream. -> https://github.com/NebulousLabs/skystandards/pull/1/commits/9a79a658884c8b1050b2f18192f9455d9457020c

**Comment by redsolver** [comment]
@kamy22 I agree that `stream` makes more sense than `feed`, but I would prefer `page` even more, because one of these "page" objects is a single page ofcontent basically (not in the UI necessarily)

**Comment by ilkamo** [comment]
@DaWe35 @lukehmcc what is your opinion?

**Comment by DaWe35** [comment]
I had a couple of projects over the years and I don't even have a similar table structure for `users`, `posts`, or anything. I think we can standardize JSON format without limiting them (so you can have optional AND additional fields), but we need to understand how and why web2.0 apps use databases.

We also need to have some kind of interface (ok that's why I made SkyID, but plenty of room for improvement). We also need to give the ability to users to switch between SkyID versions (not an easy one).

Another thing, we also need to standardize the maximum size of files. For example, SkyID has a MB limit for profile pictures what we can verify later, so if a hacker uploads a 2GB image, it won't break SkyFeed.

**Comment by ilkamo** [comment]
@DaWe35 thanks for your opinion. Currently we are just trying to understand how model the data in order to have a standard way of implementing data structures in skynet applications. For example, having in mind how a post is structured, different apps will be able to access the same data to perform different kind of operations. We are not modeling tables. The result of our iterations should be exactly what you wrote (standardized JSON structures). Of course apps will be able to exentd these models to perform more specific operations.

This PR would be just the first of n iterations. I tend and I like to be pragmatic because our conception will evolve with the time and probably we will challenge these models different times. Future PRs will cover how JSON should be structured, will add descriptions about how things should be done using the pattern A instead of pattern B, file size limits, etc.

**Comment by redsolver** [comment]
Another thing I don't like is the word `Friend list`. A list of multiple users can be a followers, a following, a recommendations and maybe a blocking list. So I think a more generic name like `User Relation Map` or `User Relation List` makes more sense. The generic list can then have a field specifying which function it serves, but the general structure  should be the same.

**Comment by lukehmcc** [comment]
Sorry that I took so long to get to this, I was expecting to have to read through lists of different JSON formats and figure out which one made the most sense, not a folder structure XD.

I think that `streams` and `profile` make the most sense for those categories. Though, at the same time, I agree with @redsolver that something like `User Relations` would be much more fitting than `Friends List`.

**Comment by ilkamo** [comment]
I applied your suggestions. @redsolver @lukehmcc. 
Let's merge this pull request and go on with the structure definition for each section!

**Comment by redsolver** [comment]
I still think that `page` fits better than `stream`, because it literally is one page object and the name `stream` should be reserved for another thing imo, for example a collection of `page`s which combined are a full user `stream` or something. I would love to hear your reasoning behind preferring `stream`. Other than that I'm ready to merge.

**Comment by DaWe35** [comment]
@redsolver what about `feed`?

**Comment by redsolver** [comment]
> @redsolver what about `feed`?

It's just one page of a feed, so `FeedPage` could fit. `feed` makes sense for a full collection of multiple feed pages with some extra metadata

**Comment by ilkamo** [comment]
I pushed changes with a `Feed Page` -> https://github.com/NebulousLabs/skystandards/pull/1/commits/44840a357e53bf8e8ea113a84ed1f39e9d311b2c. Remember that it can be easily renamed if we change our mind during the schema definition. @redsolver @DaWe35 @lukehmcc

**Review by redsolver — APPROVED** [review]

**Review by DaWe35 — APPROVED** [review]

**Comment by redsolver** [comment]
@kamy22 Do you want to merge?

**Pull request merged**
